# Uncomment the next line to define a global platform for your project
# platform :ios, ’10.0’

target 'ChatRoom' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ChatRoom

pod 'Firebase/Database'
pod 'Firebase/Auth'
pod 'Firebase/Storage'
pod 'GoogleSignIn'
pod 'FoldingCell','~>2.0.3'
end
