
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'testLogin' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks

  use_frameworks!

  # Pods for testLogin
pod 'Firebase'
pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'Firebase/Core'
pod 'GoogleSignIn'

  target 'testLoginTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'testLoginUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
